version: '3.8'
services: 
    database:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        
        environment:
            - POSTGRES_DB=database-rukesh
            - POSTGRES_USER=rukesh-shrestha
            - POSTGRES_PASSWORD=rukeshshrestha

    web:
        build: .
        command: python /CP4/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/CP4
        ports: 
            - 8000:8000
        depends_on: 
            - database
volumes: 
    postgres_data:

