version: '3.8'
services: 
    databases:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=rukesh-databases
            - POSTGRES_USER=rukesh-shrestha
            - POSTGRES_PASSWORD=rukeshshrestha
    web:
        build: .
        command: python /CP5/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/CP5/
        ports: 
            - 8000:8000
        depends_on: 
            - databases
volumes: 
    postgres_data:


