version: '3.8'
services: 
    database:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    web:
        build: .
        command: python /CP3/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/CP3
        ports: 
            - 8000:8000
        depends_on: 
            - database
volumes: 
    postgres_data: