version: '3.8'

services:
    db:
        image: postgres:12
        volumes:
        - ./data/db:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        
    web:
        build: .
        command: python /CP2/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/CP2
        ports: 
            - 8000:8000
        depends_on: 
            - db


        
     