version: '3.8'
services:
    databases:
        image: postgres:11
     
        environment: 
            - POSTGRES_DB=<db name>
            - POSTGRES_USER=<db username>
            - POSTGRES_PASSWORD=<db password>
        
            
    web:
        build: .
        command: python /CP6/manage.py runserver 0.0.0.0:8000
        # command: gunicorn staticfiles.wsgi -b 0.0.0.0:8000
       
        ports: 
            - 8000:8000
        environment: 
            - ENVIRONMENT=production
            - SECRET_KEY=rukshrbb45789@GMAIL_RUKEHOHB(hjde)hubefbewbf234418&&sdfsdfjsdbfbsdfbsdbjfbfjduefe@!*#fb3uw4890bwbw5jjsfbjhe-=-1=efb3#%@^&omo9ug3nk&pw%p-5@zuig1u&$_=lbnduhd%%q1oh!h&puxyyg
            - DEBUG=1
            - STRIPT_TEST_PUBLISHABABLE_KEY=<key>
            - STRIPT_TEST_SECRET_KEY=<key>
            - EMAILHOSTPASSWORD=<password>
            - DEFAULTEMAIL=<defaut email>
            - EMAILHOST=<host name>
            - EMAILHOSTUSER=<user host>
        depends_on: 
            - databases

